import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Brush, ClipboardCheck, PackageOpen, PenTool, Search, Truck } from "lucide-react";
import { CTA } from "@/components/CTA";

export const metadata: Metadata = { title: "OEM & ODM Custom Nail Manufacturing", description: "Custom press-on nail design, sampling, private label packaging and bulk production." };

export default function OemPage(){
 const steps=[{i:<Search/>,n:"01",t:"Market & Brief",d:"Share target customer, reference designs, target cost, order quantity and launch timing."},{i:<PenTool/>,n:"02",t:"Design Development",d:"We refine shapes, colors, patterns, decorations and product configuration."},{i:<Brush/>,n:"03",t:"Sample Making",d:"Physical samples are produced for visual, fit and packaging review."},{i:<ClipboardCheck/>,n:"04",t:"Approval",d:"Confirm approved sample, specifications, artwork, quantities and timeline."},{i:<PackageOpen/>,n:"05",t:"Production & Packing",d:"Bulk production, accessory assembly, labeling and retail packaging."},{i:<Truck/>,n:"06",t:"Inspection & Shipping",d:"Final checks and shipment by courier, air or sea according to your needs."}];
 return <><section className="page-hero gradient-hero"><div className="container narrow"><span className="eyebrow">OEM / ODM SERVICE</span><h1>Build a Nail Collection That Belongs to Your Brand</h1><p>Choose full customization or adapt our production-ready styles with your colors, logo and package.</p><Link className="button" href="/contact">Start a Custom Project <ArrowRight size={18}/></Link></div></section><section className="section"><div className="container"><div className="timeline-grid">{steps.map(s=><div className="timeline-card" key={s.n}><div className="timeline-icon">{s.i}</div><span>{s.n}</span><h3>{s.t}</h3><p>{s.d}</p></div>)}</div></div></section><section className="section section-soft"><div className="container split-grid"><div><span className="eyebrow">WHAT CAN BE CUSTOMIZED</span><h2>Every visible part of the product can support your positioning.</h2></div><div className="custom-list">{["Nail material, thickness and flexibility","Shape, length, curvature and size range","Base color, printing, chrome, glitter and cat-eye effects","Hand-painted art, charms, rhinestones and 3D decorations","Logo, box, tray, instruction card and accessory kit","Barcode, warning labels, batch information and carton marks"].map(x=><div key={x}><span>✓</span>{x}</div>)}</div></div></section><CTA/></>;
}
